version: "3"
services:
  backend:
    depends_on:
      - pg
    container_name: "backend"
    build: ./backend/
    ports:
      - "3001:3001"
    env_file:
      - .env
    networks:
      - network
    restart: on-failure

  frontend:
    depends_on:
      - pg
      - backend
    container_name: "frontend"
    build: ./frontend/
    ports:
      - "3000:3000"
    networks:
      - network
    restart: on-failure
    
    
  pg:
    container_name: "postgres"
    build: ./database/
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pg-db:/var/lib/postgresql/data
    networks:
      - network


networks:
  network:

volumes:
  pg-db:
    driver: local
    name: pg-db
    driver_opts:
      type: none
      o: bind
      device: /Users/$USER/docker_volume
